name: Release

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write  # Ensure write access to release and contents

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Build the project'
        run: npm run build

      - name: 'Zip build folder'
        run: zip -r chrome-plugin.zip build/chrome-plugin

      - name: 'Create GitHub Release and Upload Asset'
        uses: softprops/action-gh-release@v1
        with:
          files: chrome-plugin.zip  # Upload the zipped build file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication